### ISSUE TITLE
run spring boot

### ISSUE THREAD

**Issue by rodesousa** [Treydone/mandrel#2]
Au moment d'un "mvn spring:boot run -DskipTests"
Je me tape l'erreur suivante : 

[INFO] Scanning for projects...
[INFO] Searching repository for plugin with prefix: 'spring'.
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] The plugin 'org.apache.maven.plugins:maven-spring-plugin' does not exist or no valid version could be found
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: < 1 second
[INFO] Finished at: Thu Feb 11 15:46:56 CET 2016
[INFO] Final Memory: 5M/150M

**Comment by rodesousa** [comment]
Mon intellij avait du mal a synchro avec org.apache.maven.plugins pour le maven-source-plugin . J'ai lancé le dl des dépendances à la main, et Intellij reconnait enfin :D

Par contre toujours même erreur :/
De plus y'a pas une seule trace de l'artifact maven-spring-plugin dans mandrel

**Comment by Treydone** [comment]
There was a mistake in the doc, this is not "mvn spring:boot run -DskipTests", but "mvn spring-boot:run -DskipTests". The doc has been updated ;)

**Comment by Treydone** [comment]
Issue closed
