### ISSUE TITLE
Problem with git-commit-id-plugin

### ISSUE THREAD

**Issue by rodesousa** [Treydone/mandrel#6]
I had to comment the version of git-commit-id-plugin, I had the following error when i compiled mandrel:

[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.0:revision (default) on project core: The plugin pl.project13.maven:git-commit-id-plugin:2.2.0 requires Maven version [3.1.1,) -> [Help 1]

After comment, i can compile.

**Comment by Treydone** [comment]
Ok, can you try with the version 2.1.15? The 2.2.0 has some major changes, but I was not aware of the Maven compatibility.

**Comment by rodesousa** [comment]
No, 2.1.15 same error.

**Comment by Treydone** [comment]
Maven 3.1.1 was released in 2013 and is no more recommanded, Mandrel use Maven 3.3+, the documentation is updated with the compatibility.
